version: '2'
services:
    nest_api:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 3000:3000
            - 9229:9229
        depends_on:
            - postgres-service
    postgres-service:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - 5432:5432
    pgAdmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - 5050:80
volumes:
    postgres:
    pgadmin:
